version: "3.7"

services:
  esowc-wildfire:
    build:
      args:
        - username=${USER}
        - uid=${UID}
        - gid=100
      context: ../
      shm_size: '4gb' #shared memory for build
      dockerfile: docker/Dockerfile
    shm_size: '10gb' #shared memory for run
    ports:
      - "8080:8888"
    volumes:
      - ../data:/home/${USER}/app/data
      - ../examples:/home/${USER}/app/examples
      - ../docs:/home/${USER}/app/docs
      - ../src:/home/${USER}/app/src
    init: true
    stdin_open: true
    tty: true 
