version: "3.7"

services:
  jupyterlab-server:
    build:
      args:
        - username=${USER}
        - uid=${UID}
        - gid=${GID}
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - ../data:/home/${USER}/app/data
      - ../examples:/home/${USER}/app/examples
      - ../docs:/home/${USER}/app/docs
      - ../src:/home/${USER}/app/src
    init: true
    stdin_open: true
    tty: true 