version: "3.7"

services:
  jupyterlab-server:
    build:
      args:
        - username=${USER}
        - uid=${UID}
        - gid=${GID}
      context: ../
      shm_size: '2gb'
      dockerfile: docker/Dockerfile
    shm_size: '2gb' #this is the maximum memory provided by mybinder
    ports:
      - "8888:8888"
    init: true
    stdin_open: true
    tty: true 
